[package]
name = "kvs-server"
version = "0.1.0"
edition = "2018"

[dependencies]
kvs = { path = "../kvs" }
structopt = "0.3.1"
slog = "2.5.2"
slog-json = "2.3.0"
log = "0.4.8"
clap = "2.33.0"
sled = "0.22.1"
env_logger = "0.6.2"
